apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ipacerts.cert.patrickeasters.com
spec:
  group: cert.patrickeasters.com
  names:
    kind: IpaCert
    listKind: IpaCertList
    plural: ipacerts
    singular: ipacert
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
